### ISSUE TITLE
package.json for npm

### ISSUE THREAD

**Issue by ryuran** [kaelig/hidpi#5]
Hello Kaelig

Bower will disappear, so can you add npm (and/or gem) support ?

Thanks

**Comment by kaelig** [comment]
Thank you for asking!

AFAIK, it doesn't look like Bower is going anywhere anytime soon, and I don't feel like maintaining this project (I recommend using SVG instead of relying on media queries for loading high resolution images in the UI, and the picture element/srcset to deal with content images). 

Feel free to take over with your own fork and submit it to the npm registry!

**Comment by ryuran** [comment]
It's what i will do ^^ thanks
